sudo: false
language: java

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

notifications:
  email: false
  slack:
    on_failure: always
    on_success: never
    on_pull_requests: false
    rooms:
      secure: mWzYwXXkaPJ/t24kG9gz6hYyRGoGX+zsjKDa+IzjhY4NeMJyzgHyN3x1vWwSXhfG1jQuBTFyT5RTWN8Jfo2Za/XDKYfMXXP5gCMtNkeWdflYWaUC7sAZepRANUB3gzkCTvkc/DOY/FI07xCcLMJoZ7jGiADNakTaWvzdExJUBs6NuhGdIUmOT+chbip02yN7mSPeqyU7/vFqpCxxEoPeNzaNshLufbZUEWgmLm0bm5Uxdo7Yi5rL0/nA7oqXUzzWTtgQEu0mOG4Oqu7oXAki2rLISw8enZwt5/fUbxGgK1J3UB86vgnDrxbTAhuNUuddaSxUuDsg1+3xyRzU74cyKUWnWqL10Tyy9KgDR0A+48w2v8DH/pOvnvfXA+FL0zLtDJ9jPuSK0dFbceRYmolEGMDF53Q/s2W+waC13Bi3nHRQJKYmT+bOnoLABLpfm5fbV/2br4LVTQwiP80HJ+19Vy4lriF55zu1yjESUBzdvvX1Dhp5E3AXZZv6xB0v4gyZZeOoIv6BxqinLauZiS3nM7O9vu1QnFvbo4HH0Df651fyy1kOU5UAAD+CNRgpZ8GMc+EegvnLbS3nzbNOPlkACmhxMNcpEvD6MomcB4UV2dPWAYIQSfrRV5h+iZlNSqCkA2pl3p6TTZhLMvoSxziRzUZZx7GQe/cnUGN6GbzyyRk=

install: true
script: ./mvnw verify --show-version --batch-mode --errors

before_deploy:
  - ./mvnw clean verify --show-version --batch-mode --errors -Drevision=$TRAVIS_TAG
  - cd $TRAVIS_BUILD_DIR/distribution/target
  - sha256sum teamcity-snyk-security-plugin.zip > teamcity-snyk-security-plugin.zip.sha256
  - cd $TRAVIS_BUILD_DIR
deploy:
  # GitHub releases
  - provider: releases
    api_key:
      secure: Wtq5M5i2CbkpfiF3ZRzqWWlWk7ofn45TuXszeIHlz5ZpiipkEfGp/2+tc5eGJk3tq7fVRcfB0S9a7NzSyEOwwK7MqcQr8ydzAMFDJ8kdOM7zfyhoPlRt2CGoxJvqhowmU7e5nkLtyJrewS1d1k0lcqmpD85JMVykcaIDWciJ3whARwld6Gvg7EHt5dfFrEuNLeQgxI/q+ASPne52MfGC61euL9ippq2Pw3N4xEmRQzUDVsz4fpJIQrNg3nRNqMdVBC/L6If9ph1I3WKCbyaZBXsqz8sKWuOd+7zGwaQJCd4/Muplo4N2J7AI5Uespr8dUn97j7TuYsqFmwlCOfWUn/iRVKWGfrucPWbelNdXVbRBKXF4einGOnsf9UYyb9XI3Z9R4nMN19B+DHKGsKQL08v2FDyIO0au40XgWUza8cq5+hEFpVuc3i353cEVUCCVhvnLKyYGkX+07HL+bVDBI4h9PZRH/iM6QsigrXuC200Ss8hyZ4/7miJK7RwhrKQTTcZgtM7M5yahaVjtn/hpgstdDH/5RruCri7/qRwgAtfvgNLcC4mnpqHbfhHvhGRDJikOmInJnCiW9T6q3gmCaZqoRoPGkywToYxQDDbmw039/diy/09GK/JjmZOFSZJ1w9mH+ESjGRcK2bZxpThzDCdkbqTkQ77e/AHcCR+y/CA=
    file:
      - distribution/target/teamcity-snyk-security-plugin.zip
      - distribution/target/teamcity-snyk-security-plugin.zip.sha256
    skip_cleanup: true
    on:
      repo: snyk/teamcity-snyk-security-plugin
      tags: true
  # JetBrains plugin portal
  - provider: script
    script: >-
      echo "Deploying the plugin to JetBrains Portal..." &&
      curl -i --header "Authorization: Bearer $JETBRAINS_PUBLISH_TOKEN" -F pluginId=12227 -F file=@distribution/target/teamcity-snyk-security-plugin.zip https://plugins.jetbrains.com/plugin/uploadPlugin
    skip_cleanup: true
    on:
      repo: snyk/teamcity-snyk-security-plugin
      tags: true
