version: "3.7"
services:

  server:
    image: "jetbrains/teamcity-server:2018.2.3"
    ports:
      - "8111:8111"
    volumes:
      - "./distribution/docker/data:/data/teamcity_server/datadir"
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx512m"
